### ISSUE TITLE
Material icons have too long loading times

### ISSUE THREAD

**Issue by fsandelin** [antoncarlsson/cloudnews#128] opened 2018-11-30 09:49 UTC
It loads the "reply" icon from somewhere when displaying. Should maybe already be loaded?

**Comment by fsandelin** [comment] 2018-11-30 10:02
![capture](https://user-images.githubusercontent.com/14057288/49282410-682bc600-f48f-11e8-8e07-cdf6337080ae.PNG)

**Comment by kramstrom** [comment] 2018-11-30 10:35
This is not a bug, it's intended behaviour, if you are offline the website won't load anyway.

**Comment by kramstrom** [comment] 2018-11-30 10:49
All material icons should be pre-loaded in production, however, for dev this is fine

**Comment by kramstrom** [comment] 2018-12-11 14:17
Some icons don't work for offline use, closing this

**Closed by kramstrom** 2018-12-11 14:17 UTC
Labels: Design
